baseURL = 'https://wkiym.github.io/blog_test/'
languageCode = 'ja-jp'
title = 'blog_test'
theme = 'ananke'
relativeURLs = true
canonifyURLs = true

[params]
  description = "Hugo + GitHub Pages テストサイト"
  mainSections = ["posts"]
